const winnerResponses = {
  week1: {
    question: `You observe that a fellow student in your hostel seems withdrawn and has stopped participating in activities they once enjoyed. You are not close friends, but you are concerned. What could be some thoughtful ways you might reach out, or what small steps could you take to support them, keeping in mind the mental health resources and culture at NIT Jalandhar?`,
    response: `Taking an example of a boy in my hostel who used to play guitar but now has stopped doing it.First of all I will try to talk to him casually during the time when he is not in his room, like in mess or somewhere else. During the conversation, I will ask him, "Bhai yaar bde din ho gye, tere room se guitar ki aawaz nhi suni." Then he will definitely not tell me the exact reason as he is not my close friend. But I will observe him while answering the question and will get to know whether he is busy doing something else or he is mentally or physically ill. Also I will confirm the matter from his roommate or any of his close friends whom I know. CASE 1: He is busy somewhere else and is not getting enough free time. SOLUTION: Everything is ok. Nothing needs to be done. CASE 2: He is going through some physical illness. SOLUTION: I will make sure that he has got himself examined by the doctors of the institute dispensary and is taking proper medications. I will frequently visit his room to know his recovery status. I will share institute ambulance number with him which he may require in case of emergency. Also, if required, I will inform the hostel attendant about his health problem. CASE 3: He is going through some psychological issue (depression, inferiority complex, stress, loneliness etc.). SOLUTION: I will increase my frequency of talking to him. I will encourage him to share his feelings openheartedly either with me or anyone else. I will make him aware about the CONNECT portal provided to every student of NITJ on ERP. I will also encourage him to visit the psychologist available in the institute. But the most effective solution in this case will be to spend some quality time with his friends. He may go to a trip to get a break. He may get into some sports activities, and enusre he isn't left alone`,
  },
  week2: {
    question: `Your room mate is stuck in a loop and cannot focus on her/ his  studies because of a constant worry about the uncertainty of the future. Everytime he opens his books the thoughts about what his life is going to look like … what job he will get… whether his parents expectations will be met… the overthinking in the loop goes on and on.The result is that the stress keeps on increasing and he keeps procrastinating the schedule of study which is planned and he lags behind in project work, assignments and preparing for exams.
How will you help this person 
1) get on track with work.
2) reduce the feeling of worry that is interfering with ability to work.
3) break this pattern of procrastination which is now becoming a habit.`,
    response: `Last semester one of my roommate was worried all the time about his future and studies. He kept thinking about jobs, parents, and failing exams. Every time he tried to study, he got stuck and ended up wasting time. It became a habit, and he started falling behind in classes. One day, I just sat down with him and asked what was going on. He said he felt lost and didn’t know how to start. So we made a small plan together: -We started with simple tasks, like reading a few pages or solving one question. We didn’t think about the whole syllabus just one thing at a time. After finishing, we took breaks and talked about anything but studies. It made everything less stressful. -We went to the library together. Just sitting with someone helped both of us stay off our phones and actually study. We shared small goals, like “I’ll finish two chapters,” and cheered each other on when we got them done. -Some days he still got anxious. We would go outside for a short walk or sit quietly for a few minutes. Sometimes talking about our worries helped. We also made jokes about our past mistakes, which made things feel normal. Slowly, he started finishing his assignments and felt better. We never did anything fancy just kept trying, helped each other, and didn’t give up. That’s how we broke the loop and started moving forward. I think the best way to help is just to listen, be there, and do things together. Small steps, every day. That’s what worked for us, and I believe it can help others too.`,
  },

  week3: {
    question: `A friend confided in me about his relationship. He felt as if he was doing too much and she wasn’t completely into him. He lived in insecurity that she would soon give up on him and he would be lonely again. He also confessed that this was a pattern he was in and was in and out of several relationships… so much so that he really didn’t know what he was really looking for or if the relationships were just a series of rebounds. He felt empty and emotionally overwhelmed most of the time. He had begun to doubt himself and realised that he was losing sleep and his mind over his relationship.
What advice will you give him?`,
    response: `Self worth should be the floor, not the ceiling. Wanting steady love and clear effort is not asking for too much, it is asking for what's healthy. "We accept the love we think we deserve" said to his student Charlie by Mr. Anderson in a movie we all know and honestly, truer words were never spoken. Any relationship, including friendships should be reflective like a mirror. If the effort, affection and attention are not reciprocated then regardless of where the fault lies, it most definitely does not lie with you. Then again my friend, the heart wants what it wants. One cannot and must not completely blame the other person for not being involved fully without understanding their side either but if they cannot be present themselves in full capacity right now, it is a sign to be the bigger person, protect your heart, wish them well and be patient until you come across someone who gives you reason to wake up everyday instead of taking away your sleep and peace of mind. At the same time, you cannot pour from an empty cup, clinging on to past relationships will keep you from refilling your cup. Letting go is the ultimate act of self, and before anyone, your loyalties lies with your own mind and body. Communicate things as they are, express your concerns, try to fix things but if nothing seems to work out then choose gentleness with yourself without guilt. Because in your world nothing has mattered more than you and nothing ever will.`,
  },
  week4: {
    question: `My concern this week is about buckets full of time wasted by me each and every day… I know I have so much work to do but yet I cannot give up lazing around or scrolling unnecessarily on Instagram watching useless reels day in and day out. The result is I usually do all my work at the last minute and sometimes I get away with it but sometimes I pay a price when it affects my GPA.
I know I should make a timetable, stick to it, study regularly, finish projects on time and also start preparing for future exams which I need to appear in after my B tech. However it’s all about this habit…… I just can’t put my phone down… and neither get myself off of social media.
Please suggest strategies which will work… no gyan helps ok?? I also know that time is precious… but I can’t help myself…`,
    response: `I completely relate to this problem of wasting time on Instagram and reels instead of being productive. Since I am on the NIT Jalandhar campus, I can practically use the facilities here to fight this habit and improve my focus. One strategy I plan to use is changing my environment. Whenever I try to study in my hostel room, I end up scrolling endlessly on my phone. So, instead of forcing myself there, I will shift to the Central Library or Reading room where there are fewer distractions and I can see other students studying. For example, the library at NITJ is open till late, and whenever I sit there, I feel naturally motivated to use my time better because everyone around me is busy studying.Another concrete step is to replace my social media time with campus activities. Instead of lying on my bed and scrolling reels, I can go for a walk near the Sports Complex or join evening games like badminton or basketball. This gives me a break but also saves me from wasting hours online. I will also try the Pomodoro technique using small steps. For example, I'll set a timer in my phone (instead of opening Instagram) for 25 minutes of focused study in the Hostel Study Room and then take a 5-minute break. If I complete 3-4 such cycles, I will reward myself by going to Students Activity Centre (SAC) or having chai at the Nescafe outlet. This way, I trick my brain into looking forward to a reward after working.Lastly, since NITJ also has counselling services and mentors, I can talk to a senior or even attend the wellness sessions that are sometimes organized. Sharing my problem openly can help me stay accountable.By using campus facilities library for focus, sports for healthy breaks, SAC/Nescafe as small rewards. I can slowly reduce my phone usage and make my routine more disciplined.`,
  },
  week5: {
    question: ``,
    response: ``,
  },
};

export default winnerResponses;
